services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - PYTHONPATH=/app
      - MODEL_CACHE_PATH=/app/model_cache  
      - TRANSFORMERS_OFFLINE=1
    depends_on:
      - db
    volumes:
      - ./app:/app
      # - model_cache:/app/model_cache  
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        limits:
          memory: 2G  

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  model_cache:  
# services:
#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - DATABASE_URL=postgresql://user:password@db:5432/mydb
#       - PYTHONPATH=/app  
#     depends_on:
#       - db
#     volumes:
#       - ./app:/app 
      
#     command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

#   db:
#     image: postgres:16
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_DB=mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: