

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
    depends_on:
      - db
      
        

      # - kafka
    volumes:
      - ./app:/app/app  # Synchronisation du code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgresql/data  

  # kafka:
  #   image: bitnami/kafka:latest
  #   environment:
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  #   ports:
  #     - "9092:9092"

volumes:
  postgres_data: